### ISSUE TITLE
Question about fixes to get everything working according to the youtube video

### ISSUE THREAD

**Issue by maxild** [Zaid-Ajaj/fable-getting-started#4]
@Zaid-Ajaj I know its been a while since your last commit, but I have some questions

I watched the dev-owl video on youtube. Are the following correct

1. You need `devtool: "source-map"` in the webpack config to be able to debug App.fs?
2. Why did you change to `dist` instead of `public`, and is this the default output destination in webpack, since you just erased

```
output: {
        path: path.join(__dirname, "./public"),
        filename: "bundle.js",
    },
```

in last commit from webpack config?

Does the missing source map file have anything to do with you changing mode from `mode: "development"` to `mode: "none"` in your last commit? Is this why `main.js.map` is suddenly missing (without the `devtool: "source-map"`)?
 
I thought so because I can see you still have both `bundle.js` and `bundle.js.map` in GIT ignored. So source mapping used to be generated earlier...

## Addendum

I watched the rest of the video, and saw there used to be

```
devtool: isProduction ? 'source-map' : 'eval-source-map'
```

in the web config. I always code along any tutorial, because learning is about trying/playing not watching/reading :wink:

**Comment by Zaid-Ajaj** [comment]
Hello Morten! Indeed I've changed the source code since the video to make as simple as any webpack configuration can be which is why I mentioned that this template shouldn't be used to build production stuff but only for learning purposes. Let me go through your questions. 

> You need devtool: "source-map" in the webpack config to be able to debug App.fs?

Yes, the value `"source-map"` is one of the possible values of `devtool` where this option gives you best accuracy of the source map mapping, although it slows the build process a little bit. I made it "none" because I wanted to keep the template simple. Read about [devtool in Webpack](https://webpack.js.org/configuration/devtool/) to learn more

> Why did you change to dist instead of public

Indeed, the directory `dist` is the default output directory of webpack. This way I was able to remove even more configuration. 

> Is this why main.js.map is suddenly missing (without the devtool: "source-map")?

Exactly. In any case, you shouldn't need source maps in a production build.

### Proper debug configuration

In order to enable debugging in the template, you have set the `devtool` to `source-map` during development mode and not include it at all when in production mode. For that, you need to add a couple of things. First of all, set the mode from your package.json scripts:
```fsharp
  "scripts": {
    "build": "webpack --mode production",
    "start": "webpack-dev-server --mode development"
  }
```
Then in your webpack.config.js, you can export a function instead of static configuration which can change the configuration based on the input mode like this:
```js
var path = require("path");

var config = {
    entry: "./src/App.fsproj",
    devServer: {
        contentBase: path.join(__dirname, "./dist")
    },
    module: {
        rules: [{
            test: /\.fs(x|proj)?$/,
            use: "fable-loader"
        }]
    }
};

module.exports = (env, argv) => {
    if (argv.mode === 'development') {
        config.devtool = 'source-map';
    }

    return config;
};
```
Now using this template, you can hit F5 in VS Code and it should start in debug mode. Note that is still not an optimized webpack config. It is still missing stuff for development like Hot Module Replacement, but again it is not the purpose of this repository :wink:

I hope this made sense, if you have any more questions please let me know :smile:

**Comment by maxild** [comment]
@Zaid-Ajaj Thanks for the great explanation. I appreciate a friendly community where people take time to help one another.

I am not gonna use Fable in production for the near future. But I am planning to start using it for small samples, because it looks so promising :stuck_out_tongue_winking_eye: And who know, maybe I will get something done, that will be of use to others...

I was kind of [asking](https://gitter.im/fable-compiler/Fable?at=5e32be5a594a0517c24ec9a3) for a roadmap for using Fable without starting with SAFE or any other full web stack on the gitter channel the other day. I will use this template, and the fable2-sample templates too. Thanks a lot!

I have experience with most of .NET, but it's been a while since I used NodeJS and client-side javascript (I have things in production using bower and gulp :flushed:). So looking forward to using webpack, react, etc...

**Comment by maxild** [comment]
@Zaid-Ajaj Also noticed I was using Live Reload when I ran the project this morning (It said that at the CLI, I think). It worked in `App.fs`, but when I changed `index.html`, I had to refresh the page in Chrome?

**Comment by Zaid-Ajaj** [comment]
> I was kind of asking for a roadmap for using Fable without starting with SAFE or any other full web stack on the gitter channel the other day. I will use this template, and the fable2-sample templates too. Thanks a lot!

Fable is completely independent of SAFE and you can use it just the same way you use TypeScript or modern compiled Javascript. It is true though that webpack, react etc. require some time getting used to. 

> Also noticed I was using Live Reload when I ran the project this morning (It said that at the CLI, I think). It worked in App.fs, but when I changed index.html, I had to refresh the page in Chrome?

That's right, `index.html` is not taken into account when in the Hot Reloading processes because it is not part of the compilation. If you were using [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/), then it can be added as an asset of the compilation pipeline (and reloads when changed)
